# Generated by Django 5.2.8 on 2025-11-16 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('student', '0002_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Nhận xét/Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to='classes.class', verbose_name='Lớp học')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to='student.student', verbose_name='Sinh viên')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên')),
            ],
            options={
                'verbose_name': 'Nhận xét giáo viên',
                'verbose_name_plural': 'Nhận xét giáo viên',
                'ordering': ['-created_at'],
            },
        ),
    ]
