# Generated by Django 5.2.8 on 2025-11-16 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=20, unique=True, verbose_name='Mã lớp')),
                ('ten_lop', models.CharField(max_length=100, verbose_name='Tên lớp')),
                ('nam_hoc', models.CharField(default='2024-2025', max_length=20, verbose_name='Năm học')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('giao_vien_chu_nhiem', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_managed', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên chủ nhiệm')),
                ('students', models.ManyToManyField(blank=True, related_name='classes', to='student.student', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'ordering': ['ma_lop'],
            },
        ),
    ]
