# Generated by Django 5.2.5 on 2025-12-04 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mon', models.CharField(max_length=20, unique=True, verbose_name='Mã môn')),
                ('ten_mon', models.CharField(max_length=100, verbose_name='Tên môn học')),
                ('so_tin_chi', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Số tín chỉ')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'ordering': ['ma_mon'],
            },
        ),
        migrations.CreateModel(
            name='StudentGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoc_ky', models.CharField(choices=[('1', 'Học kỳ 1'), ('2', 'Học kỳ 2'), ('3', 'Học kỳ hè')], max_length=1, verbose_name='Học kỳ')),
                ('nam_hoc', models.CharField(default='2024-2025', max_length=20, verbose_name='Năm học')),
                ('gpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='GPA')),
                ('tong_tin_chi', models.IntegerField(default=0, verbose_name='Tổng tín chỉ')),
                ('tong_diem_tich_luy', models.FloatField(default=0.0, verbose_name='Tổng điểm tích lũy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpa_records', to='student.student', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'GPA học kỳ',
                'verbose_name_plural': 'GPA học kỳ',
                'ordering': ['-nam_hoc', 'hoc_ky'],
                'unique_together': {('student', 'hoc_ky', 'nam_hoc')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoc_ky', models.CharField(choices=[('1', 'Học kỳ 1'), ('2', 'Học kỳ 2'), ('3', 'Học kỳ hè')], max_length=1, verbose_name='Học kỳ')),
                ('nam_hoc', models.CharField(default='2024-2025', max_length=20, verbose_name='Năm học')),
                ('diem_qua_trinh', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Điểm quá trình')),
                ('diem_giua_ky', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Điểm giữa kỳ')),
                ('diem_cuoi_ky', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Điểm cuối kỳ')),
                ('diem_tong_ket', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Điểm tổng kết')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student.student', verbose_name='Sinh viên')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Điểm số',
                'verbose_name_plural': 'Điểm số',
                'ordering': ['-nam_hoc', 'hoc_ky', 'subject'],
                'unique_together': {('student', 'subject', 'hoc_ky', 'nam_hoc')},
            },
        ),
    ]
