# Generated by Django 5.2.5 on 2025-12-04 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã môn học')),
                ('name', models.CharField(max_length=100, verbose_name='Tên môn học')),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Số tín chỉ')),
                ('subject_type', models.CharField(choices=[('compulsory', 'Bắt buộc'), ('elective', 'Tự chọn')], default='compulsory', max_length=20, verbose_name='Loại môn học')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Quản lý môn học',
                'db_table': 'subjects',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubjectPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='subjects.subject', verbose_name='Môn học tiên quyết')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='subjects.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Môn học tiên quyết',
                'verbose_name_plural': 'Quản lý môn học tiên quyết',
                'db_table': 'subject_prerequisites',
                'unique_together': {('subject', 'prerequisite_subject')},
            },
        ),
    ]
